// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxPersonnelManagement.Data;

#nullable disable

namespace TaxPersonnelManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001160213_AddRotationRecords")]
    partial class AddRotationRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("TaxPersonnelManagement.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.DisciplineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DisciplineTypes");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.EvaluationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionAgency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("EvaluationRecords");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.IncomeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncomeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IncomeRecords");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.LeaveHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationDays")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeaveYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemNote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("LeaveHistories");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentResidence")
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentSalaryCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrentSalaryStep")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedWorkHistory")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisciplineDecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisciplineDecisionNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisciplineReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisciplineType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulationTitles")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExceedFramePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExpectedSalaryIncreaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hometown")
                        .HasColumnType("TEXT");

                    b.Property<string>("ITSkillLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityCardPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageSkillLevel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaveCalculationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextSalaryStepDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PartyEntryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PartyOfficialDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliticalTheoryLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionAllowance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PositionCalculationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PositionDecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("RankCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardForms")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryHistoryLog")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryIncreaseDelayType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SalaryReservationDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateManagementLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TaxAuthorityStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAnnualLeaveDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("University")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PersonnelDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraduationYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainingForm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("PersonnelDegrees");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PersonnelTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("TrainingClassId");

                    b.ToTable("PersonnelTrainings");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PlanningPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanningPositions");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PlanningRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evaluation3Years")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlannedPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannedTransitionPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningTerm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliticalTheoryLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingLevel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("PlanningRecords");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PlanningTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanningTerms");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.RankSalarySpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RankSalarySpecs");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.RotationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromDepartment")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RotationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToDepartment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("RotationRecords");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.SalaryDelayReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalaryDelayReasons");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.SalaryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coefficient")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExceedFramePercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SalaryCalculationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryStep")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("SalaryRecords");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.TrainingClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionUnit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ParticipationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrainingClasses");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Administrator",
                            PasswordHash = "admin",
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.EvaluationRecord", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany("EvaluationRecords")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.LeaveHistory", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany("LeaveHistories")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PersonnelDegree", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany("PersonnelDegrees")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PersonnelTraining", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxPersonnelManagement.Models.TrainingClass", "TrainingClass")
                        .WithMany("PersonnelTrainings")
                        .HasForeignKey("TrainingClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");

                    b.Navigation("TrainingClass");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.PlanningRecord", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.RotationRecord", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.SalaryRecord", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany("SalaryRecords")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Personnel", b =>
                {
                    b.Navigation("EvaluationRecords");

                    b.Navigation("LeaveHistories");

                    b.Navigation("PersonnelDegrees");

                    b.Navigation("SalaryRecords");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.TrainingClass", b =>
                {
                    b.Navigation("PersonnelTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
