// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxPersonnelManagement.Data;

#nullable disable

namespace TaxPersonnelManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TaxPersonnelManagement.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.LeaveHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationDays")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("LeaveHistories", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentSalaryCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrentSalaryStep")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedWorkHistory")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmulationTitles")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExceedFramePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExpectedSalaryIncreaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("ITSkillLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityCardPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageSkillLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextSalaryStepDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PartyEntryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PartyOfficialDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliticalTheoryLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionAllowance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PositionCalculationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PositionDecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("RankCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardForms")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryHistoryLog")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryIncreaseDelayType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SalaryReservationDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateManagementLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TaxAuthorityStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAnnualLeaveDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("University")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personnel", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ranks", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.RankSalarySpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryStep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RankSalarySpecs", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.SalaryDelayReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalaryDelayReasons", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.SalaryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextIncreaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalaryLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("SalaryRecords", (string)null);
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Administrator",
                            PasswordHash = "admin",
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.LeaveHistory", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany("LeaveHistories")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.SalaryRecord", b =>
                {
                    b.HasOne("TaxPersonnelManagement.Models.Personnel", "Personnel")
                        .WithMany("SalaryRecords")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("TaxPersonnelManagement.Models.Personnel", b =>
                {
                    b.Navigation("LeaveHistories");

                    b.Navigation("SalaryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
